#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header DPI

if package_exists vyatta-dpi; then
    dpi --info
else
    echo "DPI is not installed"
fi
